owner: nxthdr
repo: upptime

sites:
  - name: "[v4] nxthdr.dev"
    url: https://nxthdr.dev
  - name: "[v6] nxthdr.dev"
    url: https://nxthdr.dev
    ipv6: true
  - name: "[v4] blog.nxthdr.dev"
    url: https://blog.nxthdr.dev
  - name: "[v6] blog.nxthdr.dev"
    url: https://blog.nxthdr.dev
    ipv6: true
  - name: "[v4] docs.nxthdr.dev"
    url: https://docs.nxthdr.dev
  - name: "[v6] docs.nxthdr.dev"
    url: https://docs.nxthdr.dev
    ipv6: true
  - name: "[v4] geofeed.nxthdr.dev"
    url: https://geofeed.nxthdr.dev
  - name: "[v6] geofeed.nxthdr.dev"
    url: https://geofeed.nxthdr.dev
    ipv6: true
  - name: "[v4] peers.nxthdr.dev"
    url: https://peers.nxthdr.dev
  - name: "[v6] peers.nxthdr.dev"
    url: https://peers.nxthdr.dev
    ipv6: true

assignees:
  - matthieugouel

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: nxthdr upptime
  theme: dark
  introMessage: "Uptime monitor and status page for nxthdr."
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/nxthdr/upptime
