owner: nxthdr
repo: upptime

sites:
  - name: "[IPv4] nxthdr.dev"
    url: https://nxthdr.dev
  - name: "[IPv6] nxthdr.dev"
    url: https://nxthdr.dev
    ipv6: true
  - name: "[IPv4] as215011.net"
    url: https://as215011.net
  - name: "[IPv6] as215011.net"
    url: https://as215011.net
    ipv6: true

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: nxthdr upptime
  theme: dark
  introMessage: "Uptime monitor and status page for nxthdr."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/nxthdr/upptime
