owner: nxthdr
repo: upptime

sites:
  - name: "[v4] nxthdr.dev"
    url: https://nxthdr.dev
  - name: "[v6] nxthdr.dev"
    url: https://nxthdr.dev
    ipv6: true

assignees: 
  - matthieugouel

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: nxthdr upptime
  theme: dark
  introMessage: "Uptime monitor and status page for nxthdr."
  navbar:
    - title: Status
      href: /upptime
    - title: GitHub
      href: https://github.com/nxthdr/upptime
